### ISSUE TITLE
Check changes even for services

### ISSUE THREAD

**Issue by LucaGallinari** [webgriffe/SyliusUpgradePlugin#15]
It would be great to determine if, between two patches, there have been any changes to Sylius core services that are decorated/replaced in the app. Otherwise, there won't be any easier method to check for these changes besides manually comparing all the changed files with all services that you decorated/replaced.

Example:
Between Sylius x.y.z and x.j.k the service "sylius.calculator.product_variant_price" has some changes. In my app i replaced this service with my implementation like this:
```
    sylius.calculator.product_variant_price:
        class: App\Calculator\ProductVariantPrice\CompositeCalculator
        arguments:
            - '@app.calculator.product_variant_price.tier_price'
            - '@sylius.context.customer'
```
There would be a command, something like "webgriffe:upgrade:sevice-changes", that will tell you that that service could have some significant changed to tackle.

What do you think?
